### ISSUE TITLE
Plugin v 1.4.0 crashes on non-semver tags

### ISSUE THREAD

**Issue by plutarchus45** [jamesridgway/gradle-gitflow-plugin#17]
When using plugin v 1.4.0 on a repository that has non-semver tags (e.g. "blah"), the plugin fails with the following error:

> Failed to apply plugin [id 'uk.co.jamesridgway.gradle.gitflow.plugin']
   > No value present

This can be reproduced by simply adding a tag "blah" to a repository for which the plugin is working.

The same behavior is observed for version 1.3.0.

Version 1.2.0 does work (it ignores the non-semver tags and only considers the semver ones).

**Comment by jamesridgway** [comment]
I have now managed to reproduce the issue

**Comment by jamesridgway** [comment]
I believe I now have this fixed in version 1.5.2

**Comment by plutarchus45** [comment]
@jamesridgway , thanks for the fast reply and fix. Much appreciated.

I verified that 1.5.2 indeed fixes the case where a release (semver) tagged commit also contains a non-semver tag. 

I did notice however that the plugin still crashes on non-semver tags on non-release commits (i.e. commits not containing a semver-like tag as well). It depends a bit on the plugin's philosophy whether this is to be considered desired behaviour or not. I would be in favour of having the plugin deal with all non-semver tags by gracefully ignoring them.

You can find the relevant part of the experiment with 1.5.2 that I did below (using your build.gradle file above):

```
$ git tag "blah" -m "Added non-semver tag on non-release commit"
$ ./gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Build file 'gitflowexp\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'gitflowexp'.
> Failed to apply plugin [id 'uk.co.jamesridgway.gradle.gitflow.plugin']
   > No value present

$ git tag 1.0.0 -m "Added semver tag to commit already tagged by a non-semver tag"
$ ./gradlew clean build
1.0.0
BUILD SUCCESSFUL in 2s
```

When doing the steps above with 1.4.0 the last build fails, confirming the fix in 1.5.2

**Comment by jamesridgway** [comment]
@plutarchus45 , this should now be fixed under 1.5.3

Please confirm this solves your issue and I will mark this issue as resolved (or investigate further).

**Comment by plutarchus45** [comment]
Hi @jamesridgway , I tested 1.5.3 and observed the following behaviour: crashes on a non-semver tag on a non-release commit do not occur anymore BUT for such a tag a version number of 0.0.0 is generated. 

Steps to reproduce (using build file above and version 1.5.3 of the plugin):

```
$ git add NewFile
$ git commit -m "Created commit"
$ git tag 7.7.7 -m "Created semver tag to get started ..."
$ ./gradlew clean build
7.7.7
BUILD SUCCESSFUL in 4s
2 actionable tasks: 2 executed

$ touch AnotherNewFile
$ git add AnotherNewFile
$ git commit -m "Another commit"
$ ./gradlew clean build
7.7.7.1-master+sha.21c61f8
BUILD SUCCESSFUL in 4s
2 actionable tasks: 2 executed

$ git tag "blah" -m "Add non-semver tag to a non-release commit"
$ ./gradlew clean build
0.0.0
BUILD SUCCESSFUL in 4s
2 actionable tasks: 2 executed
```

I'm afraid this behaviour is potentially more harmful than the crash as it will cause the plugin to succeed while returning an inaccurate version string "0.0.0", which is typically injected in the downstream build pipeline.  Depending on the pipeline this will trigger issues that would be avoided if the plugin would fail as before (version < 1.5.3).

Desired plugin behaviour (my interpretation): ignore the non-semver tags and determine the version number based on the semver tags. In the example above the expected version number would be 7.7.7.1-master+sha.21c61f8, irrespectively of the 'blah' tag.

**Comment by jamesridgway** [comment]
You're right in that the latest issue you have found was not intended behaviour.

I've managed to reproduce your scenario and have added test coverage for this and have made the subsequent fix in 1.5.5
